# Generated by Django 6.0.4 on 2026-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
